### ISSUE TITLE
when applying hasura metadata apply - on  a fresh install, it gets a, WARN Metadata is inconsistent

### ISSUE THREAD

**Issue by Eskyee** [liquidnft/lnft#70]
been seeing this for a while.. @asoltys  to reproduce bug.. do a fresh lnft local or cloud install

WARN Metadata is inconsistent   - INFO Metadata applied

I can fix this by opening the hasura/graphql-engine:v2.0.9.cli-migrations-v3 via browser http://127.0.0.1:8080/console

You have been redirected because your GraphQL Engine metadata is in an inconsistent state
Hasura Metadata Status
GraphQL Engine metadata is inconsistent with database

then I just reload metadata..   fixes issues.
GraphQL Engine metadata is consistent with database..

cheers

**Comment by asoltys** [comment]
I'll add "hasura metadata reload" to the install steps
