### ISSUE TITLE
browser bug with navbar in Safari

### ISSUE THREAD

**Issue by Eskyee** [liquidnft/lnft#71]
the menu navbar shows broken with Apple Safari Version 14.0.2 (16610.3.7.1.9), 

but the navbar shows up correct with the chrome, browser.
just tested with FireFox navbar & shows up correct with the Firefox browser.

I think __layout is our problem ?? 

in safari dev logs....
[HMR][Svelte] – "Unrecoverable error in <__layout>: next update will trigger a full reload"

in chrome...
index.mjs:1983 <Routes> received an unexpected slot "default".

@asoltys 
I can reproduce safari bug with the master branch..

bug navbar happens in all pages with Safari browser .. at first, I thought only FAQ..
I have cleared cache .. still shows bug..
cheers
![143680630-f8bdce25-a18d-4517-8a05-58076e1ccbaf](https://user-images.githubusercontent.com/30862925/144175309-e9e7579a-badf-4ea2-9dd2-f61850b07fa0.png)

**Comment by asoltys** [comment]
@omgmanu can you reproduce this?
