### ISSUE TITLE
 GraphQL Engine metadata is inconsistent with database - with a fresh install

### ISSUE THREAD

**Issue by Eskyee** [liquidnft/lnft#75]
after testing another fresh lnft master branch with codespaces.

I found this error still ... hasura metadata apply
GraphQL Engine metadata is inconsistent with database

userstats | table | userstats | Inconsistent object: no such table/view exists in source: "userstats"

have tried to refresh.. but was left with this one error..
![Hasura Metadata Status](https://user-images.githubusercontent.com/30862925/144890826-8c80d1b2-ae97-4016-83fd-06edd61e6772.png)

have tried hasura metadata reload but still one error left.. in  GraphQL Engine  metadata is inconsistent with database

cheers @asoltys 
if you could check this..

**Comment by asoltys** [comment]
Thanks for catching this, I missed a commit with the migration when I was cherry-picking from another branch, should be fixed now https://github.com/liquidnft/lnft/commit/f3ebefe6d61e2bd78199847a5396e891c7293b15
